name: Update website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build
        run: |
          cd shaddy.dev && nix develop -c hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Push update
        run: |
          # Run only if changed
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'ShaddyDC'
            git config --global user.email 'shaddythefirst@gmail.com'
            git add .
            git commit -m "Update website with hugo"
            git push
          fi

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
