name: Update website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Build
        run: |
          cd shaddy.dev && nix develop -c hugo -D -d ../docs

      - name: Push update
        run: |
          # Run only if changed
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'ShaddyDC'
            git config --global user.email 'shaddythefirst@gmail.com'
            git add .
            git commit -m "Update website with hugo"
            git push
          fi
